# Build stage
FROM golang:1.26.3-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod .
RUN go mod download

COPY . .
RUN go mod tidy

ENV CGO_ENABLED=1 GOOS=linux GOARCH=amd64
RUN go build -o auth-cli ./auth-client

# Run stage
FROM alpine:3.19
RUN apk add --no-cache tzdata
WORKDIR /app
COPY --from=builder /app/auth-cli /app/auth-cli

ENTRYPOINT [ "/app/auth-cli" ]